### ISSUE TITLE
¿Se corrigen los datos una vez publicados?

### ISSUE THREAD

**Issue by numeroteca** [alfonsotwr/snippets#1]
Ya por fin me voy a poner a importar datos de este repositorio al de Escovid19data. Una duda, al ser los datos extraídos de los PDF, si luego se modifican ¿se van corigiendo los datos pasados o se quedan tal cual fueron en el momento de publicarse? @alfonsotwr 
El que nos interesa es sobre todo el de hospitalizados día.

**Comment by alfonsotwr** [comment]
No, no creo que se corrijan los datos una vez publicados en el PDF. Yo al menos ni intento bajar las nuevas versiones de PDF, porque me extrañaría un montón que estuvieran rehaciendo los PDF

**Comment by numeroteca** [comment]
Entonces tienen un sesgo muy grande, como se ha ido comentando últimamente, auqnue ¿quizás para los hospitalizados no lo sea tanto?

**Comment by alfonsotwr** [comment]
La interpretación de los datos ya es otro cantar
